services:
  psql:
    build:
      context: .
      target: db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shiny-lab
      POSTGRES_DB: postgres
    volumes:
      - ./sql:/sql
    ports:
      - "5432:5432"
  python:
    build:
      context: .
      target: py
    container_name: py
    depends_on:
      - psql
    environment:
      DATABASE_URL: postgresql://postgres:shiny-lab@psql:5432/postgres
    volumes:
      - ./py:/py
    ports:
      - "8501:8501"
    tty: true

