CREATE TABLE covit19_sum (
  reporting_date DATE
  , nationwide INTEGER
  , hokkaido INTEGER
  , aomori INTEGER
  , iwate INTEGER
  , miyagi INTEGER
  , akita INTEGER
  , yamagata INTEGER
  , fukushima INTEGER
  , ibaraki INTEGER
  , tochigi INTEGER
  , gunma INTEGER
  , saitama INTEGER
  , chiba INTEGER
  , tokyo INTEGER
  , kanagawa INTEGER
  , niigata INTEGER
  , toyama INTEGER
  , ishikawa INTEGER
  , fukui INTEGER
  , yamanashi INTEGER
  , nagano INTEGER
  , gifu INTEGER
  , shizuoka INTEGER
  , aichi INTEGER
  , mie INTEGER
  , shiga INTEGER
  , kyoto INTEGER
  , osaka INTEGER
  , hyogo INTEGER
  , nara INTEGER
  , wakayama INTEGER
  , tottori INTEGER
  , shimane INTEGER
  , okayama INTEGER
  , hiroshima INTEGER
  , yamaguchi INTEGER
  , tokushima INTEGER
  , kagawa INTEGER
  , ehime INTEGER
  , kochi INTEGER
  , fukuoka INTEGER
  , saga INTEGER
  , nagasaki INTEGER
  , kumamoto INTEGER
  , oita INTEGER
  , miyazaki INTEGER
  , kagoshima INTEGER
  , okinawa INTEGER
);
