name: Docker Compose Setup

on:
  push:
    branches:
      - master  # or any branch you want to trigger the workflow
  pull_request:
    branches:
      - master  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      psql:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shiny-lab
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        volumes:
          - ./sql:/sql
            # aaa
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install SQLAlchemy pandas seaborn matplotlib streamlit psycopg2-binary

      - name: Run tests
        run: |
          python py/set_data.py
