name: Docker Compose Setup

on:
  push:
    branches:
      - master  # or any branch you want to trigger the workflow
  pull_request:
    branches:
      - master  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run containers
      run: docker-compose up -d

    - name: Verify containers are running
      run: docker-compose ps
